name: Analyze Python Functions

on:
  pull_request:
    branches:
      - main
      - add-functions-checking-github-action

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install Python and dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install pyyaml

    - name: Analyze source branch
      run: |
        python tools/analyze_functions.py analyze . source_functions_info.yml

    - name: Checkout target branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}

    - name: Analyze target branch
      run: |
        python tools/analyze_functions.py analyze . target_functions_info.yml

    - name: Compare analysis results
      run: python tools/analyze_functions.py compare source_functions_info.yml target_functions_info.yml
